### ISSUE TITLE
Textblob Beispiel implementieren

### ISSUE THREAD

**Issue by ProdIsMyDev** [Covidioten/BAPraktikumSentimentAnalyse#3]
[Textblob Beispiel](https://textblob.readthedocs.io/en/dev/quickstart.html) gegen Testdatensatz laufen lassen

**Comment by InfHMoudi** [comment]
wichtig zu beachten bei Textblob ist, dass der SSH der Universität momenten Python 2 nutzt. Ich empfehle daher die Python 2 API hier zu verwenden und dann später auf Python 3 das Ende zu konvertieren.
https://textblob.readthedocs.io/en/dev/api_reference.html#

**Comment by joe-hannes** [comment]
nee hat sich erledigt, habs nur nicht hinbekommen. 
![image](https://user-images.githubusercontent.com/65351662/109775870-4f786080-7c02-11eb-93ef-19618f9d7fd1.png)
