### ISSUE TITLE
[3h] Klärung Migration der Sentiment Analyse in das Hadoop Cluster // Möglich?

### ISSUE THREAD

**Issue by ProdIsMyDev** [Covidioten/BAPraktikumSentimentAnalyse#6]
Referenz: https://github.com/aman199/Twitter-Sentiment-Analysis-Using-MapReduce

**Comment by InfHMoudi** [comment]
Es scheint möglich zu sein, siehe. https://www.researchgate.net/publication/328746218_Migration_of_Big_Data_Analysis_from_Hadoop's_MapReduce_to_Spark_AICC_2018
